materials 5
material 0 Cactus
material 1 Road
material 2 Rock
friction	0.8
skid_SM		0x00000000 // Any

material 3 Sand2
friction	0.6
rollres		3.0
collcoeff	15.0
skid_SM		0x00020047 //MW_Mod.rpk\Grass Skid
skid_SMcolor	0xFF737373
skid_PS		0x00030104 //Particles.rpk\ Sand smoke

material 4 Sand

// This material order is differend than order in 3D Max scene or .tex!!
// Get order from orginal SCM after resconvert rdb to rpk
// And make copy of your SCM (resconvert will change your file
// every time when resconverting!!)